@startuml
!define LIGHTBLUE
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml
' your UML '
 class Scritures {
     + string list<words>
     # int number
     --
     methodOne()
     --
     void secrectMoid()
 }
 class words {
    
 }
@enduml

' class exampleUse2 {
'      string dfsfd
'     --
'     methodOne()
'     --
'     void secrectMoid()
' }
' exampleUse <| -- exampleUse2
' exampleUse <-- exampleUse2
' exampleUse <-- exampleUse2
' exampleUse <.... exampleUse2
' exampleUse <-left- exampleUse2



